name: weather_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^5.3.2
  equatable: ^2.0.5

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  get_it: ^7.6.4

  intl: ^0.18.1

  loading_animation_widget: ^1.2.0+4
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/nightpic.jpg
    - assets/images/pic_bg.jpg
    - assets/images/icons8-partly-cloudy-day-80.png
    - assets/images/icons8-clouds-80.png
    - assets/images/icons8-heavy-rain-80.png
    - assets/images/icons8-rain-cloud-80.png
    - assets/images/icons8-snow-80.png
    - assets/images/icons8-storm-80.png
    - assets/images/icons8-windy-weather-80.png
    - assets/images/icons8-sun-96.png